#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
define('ROOT_PATH', __DIR__ . DS);
define('APP_PATH', ROOT_PATH . 'app' . DS);
define('RUNTIME_PATH', ROOT_PATH . 'runtime' . DS);
define('CONFIG_PATH', ROOT_PATH . 'config' . DS);

if (is_file(ROOT_PATH . 'vendor' . DS . 'autoload.php')) {
    require ROOT_PATH . 'vendor' . DS . 'autoload.php';
} else {
    die('Please run composer install.');
}

$app = new think\App();
$app->console->run();
